code/learning-ruby/ruby-on-rails-tutorial-sample-app/config/routes.rb
Rails.application.routes.draw do
  get 'home', to: "static_pages#home"
  get 'help', to: "static_pages#help"
  get 'about', to: "static_pages#about", as: "aboot"
  get 'contact-us', to: "static_pages#contact_us"
  get 'signup', to: "users#new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static_pages#home"
end

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/models/user.rb
class User < ApplicationRecord
  validates :name, length: { maximum: 50, minimum: 1 }
  validates :email, length: { maximum: 128, minimum: 1 }, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates_uniqueness_of :email

  before_save :conform_email_case

  def conform_email_case
    self.email.downcase!
  end
end

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact_us
  end
end

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page:)
    base_title = "Rails Tutorial"

    (page.nil? || page.empty?) ? base_title : "#{page} | #{base_title}"
  end
end

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/helpers/users_helper.rb
module UsersHelper
end

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    This tutorial is super cool.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", aboot_path %></li>
      <li><%= link_to "Contact", contact_us_path %></li>
    </ul>
  </nav>
</footer>

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Help",  help_path %></li>
          <li><%= link_to "About", aboot_path %></li>
          <li><%= link_to "Contact Us", contact_us_path %></li>
        </ul>
      </nav>
    </div>
  </header>

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/views/layouts/_rails_defaults.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<%= stylesheet_link_tag "application", "media": "all", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/views/layouts/application.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(page: yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= render 'layouts/rails_defaults' %>
  </head>

  <body>

  <%= render 'layouts/header' %>

  <div class="container">
    <%= yield %>
  </div>
  </body>

  <%= render 'layouts/footer' %>
</html>

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/views/static_pages/about.html.erb
<% provide(:page_title, "About") %>

<h1>ABout</h1>

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/views/static_pages/contact_us.html.erb
<% provide(:page_title, "Contact Us") %>

<h1>This is a contact us page</h1>

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/views/static_pages/help.html.erb
<% provide(:page_title, "Help") %>

<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>
  <h2>This is the home page. It's pretty boring.</h2>

  <%= link_to "Sign Up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.svg", alt: "Rails Logo", width: 200), "https://railstutorial.org" %>
<%= image_tag("kitten.jpg", alt: "Picture of kitten", width: 80) %>

code/learning-ruby/ruby-on-rails-tutorial-sample-app/app/views/users/new.html.erb
<% provide(:page_title, "Sign Up") %>

<h1>Sign Up</h1>